### ISSUE TITLE
[Feature Request] 支持自定义直播信息地址

### ISSUE THREAD

**Issue by Haocen2004** [c-basalt/bilibili-live-seeker-script#1]
在请求直播流地址的时候从指定接口请求以获取可能缓存的真原画流
e.g 参考endpoint实现 https://gist.github.com/Haocen2004/f08d68aaded40438f93204aa92e6c094

**Comment by c-basalt** [comment]
https://github.com/c-basalt/bilibili-live-seeker-script/commit/dca940545d4a7f23e85e57a020c47b0cc1b4218a

**Comment by Haocen2004** [comment]
原有测试endpoint改为私有 但提供了实现代码 如果您看到了能不能修改一下issue内容

**Comment by c-basalt** [comment]
issue可以直接看到修改历史，如果你不方便改你的endpoint那我就看看能不能把issue删了吧

**Comment by Haocen2004** [comment]
> issue可以直接看到修改历史，如果你不方便改你的endpoint那我就看看能不能把issue删了吧

endpoint准备加重定向了 把其他comment删了就行 也没多少人看history 你不说我还不知道能看（
